### ISSUE TITLE
Bold does not work

### ISSUE THREAD

**Issue by pflenker** [amitmerchant1990/reverie#5]
**bold** text passage look exactly the same as non-bold texts. Similarily, bold-and-italics can not be distinguished from italics only.

**Comment by amitmerchant1990** [comment]
It's mainly happening because I've used Futura fonts. I'm planning to replace the fonts with something more clean and aggreable in near future. Maybe something as [Libre Baskerville](https://fonts.google.com/specimen/Libre+Baskerville).

But for the time being, I suppose you'll need to replace the fonts on your own if that is the concern for you.

**Comment by pflenker** [comment]
Thanks, I'll go with my own font until you switch then, as I am also concerened about https://github.com/amitmerchant1990/reverie/issues/2 . Thanks for the great theme and keep up the good work!

**Comment by amitmerchant1990** [comment]
Cool. While you're here, I also want to let you know that I've implemented some features such as ace40eff005523026b045f942f4527187a28aa76 and 2cd5bda1a9e49fd553b000859ec3e738aa30e3f8 over this weekend. I guess you might be interested in having those in yours as well.

**Comment by pflenker** [comment]
Thanks, I will pull them in!

**Comment by amitmerchant1990** [comment]
I'd also like if you give it a ⭐️ if you like this theme. 😄Every little things counts!
