### ISSUE TITLE
How to make the header wider?

### ISSUE THREAD

**Issue by jjiantong** [amitmerchant1990/reverie#58]
Hi, I am new to this. I want to ask how can I widen the header. The main reason is that I wanna the photo to be larger. Thanks for your help.

**Comment by confor** [comment]
You can make it wider by modifying `max-width: 740px` under `.container` in `style.scss` near the top ([link](https://github.com/amitmerchant1990/reverie/blob/master/assets/style.scss#L35)). This will make the header wider but unfortunately the posts/footer will be wider too, since the whole page uses the same width.

**Comment by amitmerchant1990** [comment]
Hey @jjiantong Use the solution @confor has mentioned for now. I working on making this more seamless.
